version: '3.1'

services:
  db:
    image: mysql:5.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  web:
    build: ./web
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
